import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';
import '../config/app_config.dart';

class CowApi {
  static final String baseUrl = AppConfig.laravelApi;

  static Future<String> _getToken() async {
    final prefs = await SharedPreferences.getInstance();
    final token = prefs.getString('authToken');
    if (token == null) {
      throw Exception('Not authenticated. Please login again.');
    }
    return token;
  }

  /// PUT /api/cows/{id}  (partial profile update)
  /// Updates only weight and/or previous_disease without touching image/embedding.
  static Future<Map<String, dynamic>> updateCowProfile({
    required int cowId,
    double? weight,
    List<String>? previousDisease,
  }) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/$cowId');

    final body = <String, dynamic>{};
    if (weight != null) body['weight'] = weight;
    if (previousDisease != null) body['previous_disease'] = previousDisease;

    final response = await http.put(
      uri,
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode(body),
    );

    if (response.statusCode != 200) {
      throw Exception(
        'Failed to update cow profile: ${response.statusCode} ${response.body}',
      );
    }

    final data = jsonDecode(response.body);
    return (data['cow'] ?? data) as Map<String, dynamic>;
  }

  /// GET /api/cows/{id}/profile
  /// Returns cow + health_status, age_months, disease_detections, behavior_detections,
  /// birth_predictions, feeds, nutrition — all in one call.
  static Future<Map<String, dynamic>> getCowProfile(int cowId) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/$cowId/profile');

    final response = await http.get(
      uri,
      headers: {
        'Accept': 'application/json',
        'Authorization': 'Bearer $token',
      },
    );

    if (response.statusCode != 200) {
      throw Exception(
        'Failed to load cow profile: ${response.statusCode} ${response.body}',
      );
    }

    return jsonDecode(response.body) as Map<String, dynamic>;
  }

  /// GET /api/cows
  /// Returns a List of cow maps like:
  /// {
  ///   "id": 1,
  ///   "cow_id": "COW-001",
  ///   "name": "bella",
  ///   "birthdate": "2025-12-12",
  ///   "breed": "Holstein",
  ///   "lactation_month": 5,
  ///   "image_path": "uploads/assetImg/...",
  ///   ...
  /// }
  static Future<List<Map<String, dynamic>>> getCows() async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows');

    final response = await http.get(
      uri,
      headers: {
        'Accept': 'application/json',
        'Authorization': 'Bearer $token',
      },
    );

    if (response.statusCode != 200) {
      throw Exception(
        'Failed to load cows: ${response.statusCode} ${response.body}',
      );
    }

    final data = jsonDecode(response.body);
    if (data is! List) {
      throw Exception('Invalid cows response format');
    }

    return data.cast<Map<String, dynamic>>();
  }

  /// GET /api/cows/next-id
  static Future<String> getNextCowId() async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/next-id');
    final response = await http.get(
      uri,
      headers: {'Accept': 'application/json', 'Authorization': 'Bearer $token'},
    );
    if (response.statusCode != 200) {
      throw Exception('Failed to fetch next cow ID: ${response.statusCode} ${response.body}');
    }
    final data = jsonDecode(response.body);
    return data['next_cow_id'] as String? ?? 'C001';
  }

  /// POST /api/cows
  /// Register a new cow with image (embedding generated by Python backend)
  static Future<Map<String, dynamic>> storeCow({
    required String name,
    required File imageFile,
    String? breed,
    String? birthdate,
    int? lactationMonth,
    double? weight,
  }) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows');

    final request = http.MultipartRequest('POST', uri)
      ..headers['Accept'] = 'application/json'
      ..headers['Authorization'] = 'Bearer $token'
      ..fields['name'] = name;

    if (breed != null) request.fields['breed'] = breed;
    if (birthdate != null) request.fields['birthdate'] = birthdate;
    if (lactationMonth != null) {
      request.fields['lactation_month'] = lactationMonth.toString();
    }
    if (weight != null) request.fields['weight'] = weight.toString();

    request.files.add(
      await http.MultipartFile.fromPath('image', imageFile.path),
    );

    final streamed = await request.send();
    final response = await http.Response.fromStream(streamed);

    if (response.statusCode != 201) {
      throw Exception(
        'Failed to register cow: ${response.statusCode} ${response.body}',
      );
    }

    final data = jsonDecode(response.body);
    if (data is! Map<String, dynamic>) {
      throw Exception('Invalid store cow response format');
    }
    return data;
  }

  /// POST /api/cows/{cow}/feed
  /// This will trigger the Laravel -> Python /predict_manual flow
  /// and save the result into cow_feeds table.
  ///
  /// Expected Laravel JSON (from controller):
  /// {
  ///   "message": "Daily feed calculated and saved successfully.",
  ///   "cow_feed": {
  ///     "id": ...,
  ///     "cow_id": ...,
  ///     "cow_weight_kg": ...,
  ///     "milk_yield_l": ...,
  ///     "activity": "...",
  ///     "daily_feed_kg": ...,
  ///     "date": "YYYY-MM-DD",
  ///     ...
  ///   }
  /// }
  static Future<Map<String, dynamic>> createFeedManual({
    required int cowId,
    required double weight,
    required double milkYield,
    required String activity,
    double? ageMonths, // optional; backend can derive from birthdate if null
    DateTime? date,
  }) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/$cowId/feed');

    final body = <String, dynamic>{
      'weight': weight,
      'milk_yield': milkYield,
      'activity': activity,
    };

    if (ageMonths != null) {
      body['age'] = ageMonths;
    }
    if (date != null) {
      // YYYY-MM-DD
      body['date'] = date.toIso8601String().substring(0, 10);
    }

    final response = await http.post(
      uri,
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'Authorization': 'Bearer $token',
      },
      body: jsonEncode(body),
    );

    if (response.statusCode != 201) {
      throw Exception(
        'Failed to create feed: ${response.statusCode} ${response.body}',
      );
    }

    final data = jsonDecode(response.body);
    if (data is! Map<String, dynamic>) {
      throw Exception('Invalid manual feed response format');
    }
    return data;
  }

  /// POST /api/cows/{cow}/feed-from-image
  /// This will trigger the Laravel -> Python /predict flow
  /// based on image + form fields and save to cow_feeds.
  ///
  /// Expected Laravel JSON (from controller):
  /// {
  ///   "message": "Daily feed (image-based) calculated and saved successfully.",
  ///   "cow_feed": {
  ///     "id": ...,
  ///     "cow_id": ...,
  ///     "cow_weight_kg": ...,
  ///     "milk_yield_l": ...,
  ///     "activity": "...",
  ///     "daily_feed_kg": ...,
  ///     "date": "YYYY-MM-DD",
  ///     ...
  ///   }
  /// }
  static Future<Map<String, dynamic>> createFeedFromImage({
    required int cowId,
    required File imageFile,
    required double milkYield,
    required String activity,
    double? ageMonths,
    DateTime? date,
  }) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/$cowId/feed-from-image');

    final request = http.MultipartRequest('POST', uri)
      ..headers['Accept'] = 'application/json'
      ..headers['Authorization'] = 'Bearer $token'
      ..fields['milk_yield'] = milkYield.toString()
      ..fields['activity'] = activity;

    if (ageMonths != null) {
      request.fields['age'] = ageMonths.toString();
    }
    if (date != null) {
      request.fields['date'] = date.toIso8601String().substring(0, 10);
    }

    request.files.add(
      await http.MultipartFile.fromPath(
        'image',
        imageFile.path,
      ),
    );

    final streamed = await request.send();
    final response = await http.Response.fromStream(streamed);

    if (response.statusCode != 201) {
      throw Exception(
        'Failed to create feed from image: ${response.statusCode} ${response.body}',
      );
    }

    final data = jsonDecode(response.body);
    if (data is! Map<String, dynamic>) {
      throw Exception('Invalid image feed response format');
    }
    return data;
  }

  /// GET /api/cows/{id}/nutrition/latest
  /// Returns the most recent NutritionRecommendation for the cow (including
  /// input_data), or null if none exists yet.
  static Future<Map<String, dynamic>?> getLatestNutrition(int cowDbId) async {
    final token = await _getToken();
    final uri = Uri.parse('$baseUrl/cows/$cowDbId/nutrition/latest');

    final response = await http.get(
      uri,
      headers: {
        'Accept': 'application/json',
        'Authorization': 'Bearer $token',
      },
    );

    if (response.statusCode == 200) {
      final body = jsonDecode(response.body);
      if (body == null) return null;
      return (body as Map).cast<String, dynamic>();
    }
    return null;
  }
}